### PR TITLE
Embrace the Redirect

### PR DESCRIPTION
**Pull request by danott**
This is a GitHub pages page at https://planningcenter.github.io. Let's turn it into a pure redirect.

### CODE REVIEW

**Review by edgartheunready — APPROVED** [review]
Makes sense to me! And if we ever wanted to undo to this, `git revert` has our back. :ship: it!

**Review by seven1m — APPROVED** [review]

**Comment by danott** [comment]
For those who pay attention to detail: I added these four labels as a side-quest to make them available in Swarmia's configuration options, which is the other thing I'm working on today. 🤞

**Review by dobrite — APPROVED** [review]
The 3 links that [Google lists](https://www.google.com/search?hl=en&q=site%3Aplanningcenter.github.io) are:

* https://planningcenter.github.io/
* https://planningcenter.github.io/api-docs/
* https://planningcenter.github.io/doxy-web/

Doxy Web [is live](https://planningcenter.github.io/doxy-web/?path=/story/intro--page), but appears to be hosted via pages in [that repo](https://github.com/planningcenter/doxy-web/settings/pages).

Api docs link to our current docs [here](https://github.com/planningcenter/api-docs/blob/gh-pages/index.html).

I 99% sure those will continue to work, but would be best to verify after this PR deploys.

Also ❤️ leaving documentation for future-us.

**Comment by danott** [comment]
I used `curl https://planningcenter.github.io/doxy-web/` `curl https://planningcenter.github.io/api-docs/` and `curl https://planningcenter.github.io/` to confirm that all three pages continue working as expected.

**Pull request merged**
